#!/usr/bin/env  php
<?php

use Funkyproject\Loader\ServiceLoader;

require __DIR__.'/vendor/autoload.php';

$container = new Pimple();

$serviceLoader = new ServiceLoader($container);
$serviceLoader->load();

$application = new Funkyproject\Application($container);

$application->run();